In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
!pip install tensorflow


Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/93/21/9b035a4f823d6aee2917c75415be9a95861ff3d73a0a65e48edbf210cec1/tensorflow-2.15.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for tensorflow-intel==2.15.0 from https://files.pythonhosted.org/packages/4c/48/1a5a15517f18eaa4ff8d598b1c000300b20c1bb0e624539d702117a0c369/tensorflow_intel-2.15.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/01/e4/dc0a1dcc4e74e08d7abedab278c795eef54a224363bb18f5692f416d834f/absl_py-2.0.0-py3-none-any.whl.metadata
  Obtaining dependency information for flatbuffers>=23.5.26 from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc4b58d477b9e7/flatbuffers-23.5.26-py2.py3-none-any.whl.metadata
     ---------------------------------------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [2]:
tf.__version__

'2.15.0'

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
ann = tf.keras.models.Sequential()

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [14]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [15]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [16]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100


250/250 [==============================] - 1s 1ms/step - loss: 0.6213 - accuracy: 0.7318
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4961 - accuracy: 0.7968
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4544 - accuracy: 0.8101
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4303 - accuracy: 0.8184
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4152 - accuracy: 0.8241
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4025 - accuracy: 0.8290
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3913 - accuracy: 0.8324
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3826 - accuracy: 0.8369
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3761 - accuracy: 0.8400
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3704 - accu

250/250 [==============================] - 0s 1ms/step - loss: 0.3343 - accuracy: 0.8643
Epoch 77/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3343 - accuracy: 0.8634
Epoch 78/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3345 - accuracy: 0.8643
Epoch 79/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3341 - accuracy: 0.8650
Epoch 80/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3341 - accuracy: 0.8645
Epoch 81/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3340 - accuracy: 0.8655
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3337 - accuracy: 0.8654
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3340 - accuracy: 0.8645
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3337 - accuracy: 0.8633
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3339 - accuracy: 

In [17]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 110ms/step
[[False]]


In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1510   85]
 [ 187  218]]


0.864